#!/usr/bin/env python3
"""
RSS生成脚本
从GitHub Issues或本地数据生成RSS feed
"""

import os
import json
import xml.etree.ElementTree as ET
from xml.dom import minidom
from datetime import datetime
import pytz

def prettify(elem):
    """返回格式化的XML字符串"""
    rough_string = ET.tostring(elem, encoding='utf-8')
    reparsed = minidom.parseString(rough_string)
    return reparsed.toprettyxml(indent="    ", encoding='utf-8').decode('utf-8')

def generate_rss():
    """生成RSS XML"""
    # 创建RSS根元素
    rss = ET.Element("rss", version="2.0")
    rss.set("xmlns:atom", "http://www.w3.org/2005/Atom")
    
    channel = ET.SubElement(rss, "channel")
    
    # 频道信息
    ET.SubElement(channel, "title").text = "Jun Loye's Blog"
    ET.SubElement(channel, "link").text = "https://junloye.github.io"
    ET.SubElement(channel, "description").text = "Jun Loye 的个人博客，分享编程技术、生活点滴与思考。涵盖技术、算法与数据结构等内容"
    ET.SubElement(channel, "language").text = "zh-CN"
    ET.SubElement(channel, "lastBuildDate").text = datetime.now(pytz.UTC).strftime('%a, %d %b %Y %H:%M:%S %z')
    
    # Atom self link
    atom_link = ET.SubElement(channel, "atom:link")
    atom_link.set("href", "https://junloye.github.io/rss.xml")
    atom_link.set("rel", "self")
    atom_link.set("type", "application/rss+xml")
    
    ET.SubElement(channel, "generator").text = "GitHub Issues Blog System"
    
    # 尝试从data/config.json读取文章数据
    try:
        config_path = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), 'data', 'config.json')
        with open(config_path, 'r', encoding='utf-8') as f:
            config = json.load(f)
        
        # 假设config中有posts字段
        posts = config.get('posts', [])
        
        for post in posts:
            item = ET.SubElement(channel, "item")
            ET.SubElement(item, "title").text = post.get('title', 'Untitled')
            ET.SubElement(item, "link").text = f"https://junloye.github.io/#post-{post.get('id', '')}"
            ET.SubElement(item, "description").text = post.get('description', '')
            ET.SubElement(item, "pubDate").text = post.get('date', datetime.now(pytz.UTC).strftime('%a, %d %b %Y %H:%M:%S %z'))
            ET.SubElement(item, "guid", isPermaLink="true").text = f"https://junloye.github.io/#post-{post.get('id', '')}"
            
            # 添加分类/标签
            tags = post.get('tags', [])
            if tags:
                for tag in tags:
                    ET.SubElement(item, "category").text = tag
    
    except Exception as e:
        print(f"Warning: Could not load posts from config: {e}")
        # 添加一个默认项目
        item = ET.SubElement(channel, "item")
        ET.SubElement(item, "title").text = "RSS Feed Generated"
        ET.SubElement(item, "link").text = "https://junloye.github.io"
        ET.SubElement(item, "description").text = "RSS feed has been automatically generated by GitHub Actions."
        ET.SubElement(item, "pubDate").text = datetime.now(pytz.UTC).strftime('%a, %d %b %Y %H:%M:%S %z')
        ET.SubElement(item, "guid", isPermaLink="true").text = "https://junloye.github.io"
    
    return prettify(rss)

def main():
    """主函数"""
    print("Generating RSS feed...")
    
    # 生成RSS内容
    rss_content = generate_rss()
    
    # 写入文件
    output_path = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), 'rss.xml')
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(rss_content)
    
    print(f"RSS feed written to {output_path}")
    
    # 验证文件
    if os.path.exists(output_path):
        with open(output_path, 'r', encoding='utf-8') as f:
            content = f.read()
            if '<?xml' in content and '<rss' in content:
                print("RSS feed generated successfully!")
            else:
                print("Warning: Generated file may not be valid RSS")
    else:
        print("Error: RSS file was not created")

if __name__ == "__main__":
    main()